#!/usr/bin/env bash
#
# Patches the SPL crates for developing against a local solana monorepo
#

here="$(dirname "$0")"

solana_dir=$1
if [[ -z $solana_dir ]]; then
  echo "Usage: $0 <path-to-solana-monorepo>"
